spring.application.name=x6.user
server.port=8081
springdoc.swagger-ui.path=/swagger-ui

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/x6_user
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD:admin}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

